import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer & Liability Policy — OLADECK Global Services",
  description: "Official liability disclaimer regarding Nigeria Customs assessments, terminal demurrage, and port clearance procedures."
};

export default function DisclaimerPage() {
  return (
    <section className="py-16 md:py-24 bg-muted/20">
      <div className="container-pad max-w-4xl bg-white rounded-2xl p-8 sm:p-12 shadow-card border border-border space-y-6">
        <div>
          <p className="text-xs font-bold uppercase tracking-widest text-gold mb-1">Legal Notice</p>
          <h1 className="text-3xl font-extrabold text-navy sm:text-4xl">Customs Duty &amp; Liability Disclaimer</h1>
          <p className="mt-2 text-xs text-muted-foreground">OLADECK Global Services Limited · Licensed Customs Clearing Agent</p>
        </div>

        <div className="space-y-4 text-sm text-foreground leading-relaxed divide-y divide-border/60">
          <div className="pt-4 space-y-2">
            <h2 className="text-base font-bold text-navy">1. Customs Valuation &amp; Tariff Assessments</h2>
            <p className="text-muted-foreground">
              All duty estimates generated by OLADECK Global Services are calculated using current Nigeria Customs Service (NCS) tariff codes, vehicle age classifications, and official VIN valuation benchmarks. Final payable customs duty is determined exclusively by the Nigeria Customs Service upon physical examination at the terminal.
            </p>
          </div>

          <div className="pt-4 space-y-2">
            <h2 className="text-base font-bold text-navy">2. Shipping Line Demurrage &amp; Terminal Storage</h2>
            <p className="text-muted-foreground">
              OLADECK Global Services is not responsible for shipping line demurrage fees or terminal storage charges resulting from client delays in providing valid original documentation (Bill of Lading, Purchase Invoices, Export Title, or ID).
            </p>
          </div>

          <div className="pt-4 space-y-2">
            <h2 className="text-base font-bold text-navy">3. Vehicle Cargo Condition &amp; Pre-Existing Damage</h2>
            <p className="text-muted-foreground">
              Our terminal officers conduct a mandatory vehicle inspection upon vessel discharge. OLADECK is not liable for damages that occurred prior to vessel discharge or during ocean transit.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
